#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
Created on Dec 16, 2009 
@author: Toni Haka-Risku <tojuhaka@gmail.com>
'''


test_result = [{'custom_reference': u'Saarinen, T. (2011, 2). N\xe4kyv\xe4 ja n\xe4kym\xe4t\xf6n korkeakoulutuksen kielikoulutuspolitiikka. <em>Kieli, koulutus ja yhteiskunta. Kielikoulutuspolitiikan verkoston verkkolehti</em>. Retrieved from http://www.kieliverkosto.fi/journal/article/76/nakyva-ja-nakymaton-korkeakoulutuksen-kielikoulutuspolitiikka',
  'editors': '',
  'getRemoteUrl': 'http://tutka.jyu.fi/tutka/julkaisut/45925',
  'id': 'julkaisut_45925',
  'lib_reference': u'N\xe4kyv\xe4 ja n\xe4kym\xe4t\xf6n korkeakoulutuksen kielikoulutuspolitiikka / Taina Saarinen*. - // Kieli, koulutus ja yhteiskunta. Kielikoulutuspolitiikan verkoston verkkolehti - Jyv\xe4skyl\xe4: Jyv\xe4skyl\xe4n yliopisto 2 (2011): Toukokuu <http://www.kieliverkosto.fi/journal/article/76/nakyva-ja-nakymaton-korkeakoulutuksen-kielikoulutuspolitiikka>',
  'researcher': 'Saarinen Taina',
  'section': 'julkaisut',
  'sort_date': 2011,
  'title': u'N\xe4kyv\xe4 ja n\xe4kym\xe4t\xf6n korkeakoulutuksen kielikoulutuspolitiikka',
  'tutka_date': 2011},
 {'custom_reference': "Kalaja, P., Alanen, R. & Dufva, H. (2011). Teacher trainees' beliefs about EFL learning in the light of narratives. In S. Breidbach, D. Elsner & A. Young (Eds.), <em>Language awareness in teacher education: cultural-political and social-educational perspectives</em>.  (pp. 63-78). Mehrsprachigkeit in Schule und Unterricht (13). Frankfurt am Main: Peter Lang.",
  'editors': 'Breidbach Stephan & Elsner Daniela & Young Andrea',
  'getRemoteUrl': 'http://tutka.jyu.fi/tutka/julkaisut/45441',
  'id': 'julkaisut_45441',
  'lib_reference': "Teacher trainees' beliefs about EFL learning in the light of narratives/ Paula Kalaja*, Riikka Alanen*, Hannele Dufva*.(toim) Stephan Breidbach, Daniela Elsner, Andrea Young. - Frankfurt am Main: Peter Lang, 2011. - Mehrsprachigkeit in Schule und Unterricht; 13 - ISBN 978-3-631-61464-8",
  'researcher': 'Kalaja Paula & Alanen Riikka & Dufva Hannele',
  'section': 'julkaisut',
  'sort_date': 2011,
  'title': "Teacher trainees' beliefs about EFL learning in the light of narratives",
  'tutka_date': 2011},
 {'custom_reference': u'Kalaja, P., Palviainen, \xc5., Alanen, R., Dufva, H. (2011). Oppikirjoista, k\xe4mppiksist\xe4, teeveest\xe4 ja maitot\xf6lkeist\xe4. <em>TEMPUS</em>, 46 (3), 18-19.',
  'editors': '',
  'getRemoteUrl': 'http://tutka.jyu.fi/tutka/julkaisut/45844',
  'id': 'julkaisut_45844',
  'lib_reference': u'Oppikirjoista, k\xe4mppiksist\xe4, teeveest\xe4 ja maitot\xf6lkeist\xe4 / Paula Kalaja*, \xc5sa Palviainen*, Riikka Alanen*, Hannele Dufva*, . - // TEMPUS (toim) . - Helsinki: SUKOL 46 (2011): 3 s. 18-19',
  'researcher': u'Kalaja Paula & Palviainen \xc5sa & Alanen Riikka & Dufva Hannele & ',
  'section': 'julkaisut',
  'sort_date': 2011,
  'title': u'Oppikirjoista, k\xe4mppiksist\xe4, teeveest\xe4 ja maitot\xf6lkeist\xe4',
  'tutka_date': 2011}]



test_result2 = [{'custom_reference': u'Hemminki, A. (2010).<em> Kertomuksia avioerosta ja parisuhteen p\xe4\xe4ttymisest\xe4: suomalainen eropuhe pohjalaisten kirjoituksissa ja naistenlehdiss\xe4.</em> Jyv\xe4skyl\xe4, Finland: Jyv\xe4skyl\xe4n yliopisto. Jyv\xe4skyl\xe4 studies in education, psychology and social research, 399.',
  'editors': '',
  'getRemoteUrl': 'http://tutka.jyu.fi/tutka/julkaisut/42031',
  'id': 'julkaisut_42031',
  'lib_reference': u'Kertomuksia avioerosta ja parisuhteen p\xe4\xe4ttymisest\xe4: suomalainen eropuhe pohjalaisten kirjoituksissa ja naistenlehdiss\xe4/ Arja Hemminki*. - Jyv\xe4skyl\xe4: Jyv\xe4skyl\xe4n yliopisto, 2010. - 158 s. - Jyv\xe4skyl\xe4 studies in education, psychology and social research; 399 - ISBN 978-951-39-4048-5 (nid.)',
  'researcher': 'Hemminki Arja',
  'section': 'julkaisut',
  'sort_date': 2010,
  'title': u'Kertomuksia avioerosta ja parisuhteen p\xe4\xe4ttymisest\xe4: suomalainen eropuhe pohjalaisten kirjoituksissa ja naistenlehdiss\xe4',
  'tutka_date': 2010},
 {'custom_reference': u'Oinas, T. (2010).<em> Sukupuolten v\xe4linen kotity\xf6njako kahden ansaitsijan perheiss\xe4.</em> Jyv\xe4skyl\xe4, Finland: Jyv\xe4skyl\xe4n yliopisto. Jyv\xe4skyl\xe4 studies in education, psychology and social research, 402.',
  'editors': '',
  'getRemoteUrl': 'http://tutka.jyu.fi/tutka/julkaisut/42340',
  'id': 'julkaisut_42340',
  'lib_reference': u'Sukupuolten v\xe4linen kotity\xf6njako kahden ansaitsijan perheiss\xe4/ Tomi Oinas*. - Jyv\xe4skyl\xe4: Jyv\xe4skyl\xe4n yliopisto, 2010. - 188 s. - Jyv\xe4skyl\xe4 studies in education, psychology and social research; 402 - ISBN 978-951-39-4110-9 (nid.)',
  'researcher': 'Oinas Tomi',
  'section': 'julkaisut',
  'sort_date': 2010,
  'title': u'Sukupuolten v\xe4linen kotity\xf6njako kahden ansaitsijan perheiss\xe4',
  'tutka_date': 2010},
 {'custom_reference': u'Luomala, A. (2010).<em> Politiikan mahdollisuudesta valtuuston talousarviokokouksessa.</em> H\xe4meenlinna: Sosiaalikehitys Oy.',
  'editors': '',
  'getRemoteUrl': 'http://tutka.jyu.fi/tutka/julkaisut/42907',
  'id': 'julkaisut_42907',
  'lib_reference': u'Politiikan mahdollisuudesta valtuuston talousarviokokouksessa / Anne Luomala*. - H\xe4meenlinna: Sosiaalikehitys Oy, 2010. - 262 s. - ISBN 978-952-9820-13-5',
  'researcher': 'Luomala Anne',
  'section': 'julkaisut',
  'sort_date': 2010,
  'title': 'Politiikan mahdollisuudesta valtuuston talousarviokokouksessa',
  'tutka_date': 2010},
 {'custom_reference': u'Notko, M. (2011).<em> V\xe4kivalta, vallank\xe4ytt\xf6 ja vahingoittuminen naisten perhesuhteissa.</em> Jyv\xe4skyl\xe4, Finland: Jyv\xe4skyl\xe4n yliopisto. Jyv\xe4skyl\xe4 studies in education, psychology and social research, 406.',
  'editors': '',
  'getRemoteUrl': 'http://tutka.jyu.fi/tutka/julkaisut/43157',
  'id': 'julkaisut_43157',
  'lib_reference': u'V\xe4kivalta, vallank\xe4ytt\xf6 ja vahingoittuminen naisten perhesuhteissa/ Marianne Notko*. - Jyv\xe4skyl\xe4: Jyv\xe4skyl\xe4n yliopisto, 2011. - 254 s. - Jyv\xe4skyl\xe4 studies in education, psychology and social research; 406 - ISBN 978-951-39-4163-5 (nid.)',
  'researcher': 'Notko Marianne',
  'section': 'julkaisut',
  'sort_date': 2011,
  'title': u'V\xe4kivalta, vallank\xe4ytt\xf6 ja vahingoittuminen naisten perhesuhteissa',
  'tutka_date': 2011},
 {'custom_reference': u'S\xf6dor, U. (2011).<em> Community resilience and wellbeing in Northwest Russian forestry settlements.</em> Jyv\xe4skyl\xe4, Finland: University of Jyv\xe4skyl\xe4. Jyv\xe4skyl\xe4 studies in education, psychology and social research, 408.',
  'editors': '',
  'getRemoteUrl': 'http://tutka.jyu.fi/tutka/julkaisut/45303',
  'id': 'julkaisut_45303',
  'lib_reference': u'Community resilience and wellbeing in Northwest Russian forestry settlements/ Uuve S\xf6dor*. - Jyv\xe4skyl\xe4: University of Jyv\xe4skyl\xe4, 2011. - 195 s. - Jyv\xe4skyl\xe4 studies in education, psychology and social research; 408 - ISBN 978-951-39-4180-2 (nid.)',
  'researcher': u'S\xf6dor Uuve',
  'section': 'julkaisut',
  'sort_date': 2011,
  'title': 'Community resilience and wellbeing in Northwest Russian forestry settlements',
  'tutka_date': 2011},
 {'custom_reference': u'Kaskiharju, E. (2010).<em> Koteja ja kodinomaisuutta: tutkimus vanhenemisen paikoista valtiop\xe4iv\xe4puheissa 1950-2005.</em> Jyv\xe4skyl\xe4, Finland: Jyv\xe4skyl\xe4n yliopisto. Jyv\xe4skyl\xe4 studies in education, psychology and social research, 393.',
  'editors': '',
  'getRemoteUrl': 'http://tutka.jyu.fi/tutka/julkaisut/41557',
  'id': 'julkaisut_41557',
  'lib_reference': u'Koteja ja kodinomaisuutta: tutkimus vanhenemisen paikoista valtiop\xe4iv\xe4puheissa 1950-2005/ Eija Kaskiharju*. - Jyv\xe4skyl\xe4: Jyv\xe4skyl\xe4n yliopisto, 2010. - 244 s. - Jyv\xe4skyl\xe4 studies in education, psychology and social research; 393 - ISBN 978-951-39-3963-2 (nid.)',
  'researcher': 'Kaskiharju Eija',
  'section': 'julkaisut',
  'sort_date': 2010,
  'title': u'Koteja ja kodinomaisuutta: tutkimus vanhenemisen paikoista valtiop\xe4iv\xe4puheissa 1950-2005',
  'tutka_date': 2010},
 {'custom_reference': u'Tapio, T. (2010).<em> "Meil\xe4 on kaikila samanlaiset tarinat": tarinankerrontatutkimus tornionlaaksolaisuudesta vanhimpien aapualaisten arjessa ja tulevaisuudessa.</em> Jyv\xe4skyl\xe4, Finland: Jyv\xe4skyl\xe4n yliopisto. Jyv\xe4skyl\xe4 studies in education, psychology and social research, 395.',
  'editors': '',
  'getRemoteUrl': 'http://tutka.jyu.fi/tutka/julkaisut/41566',
  'id': 'julkaisut_41566',
  'lib_reference': u'"Meil\xe4 on kaikila samanlaiset tarinat": tarinankerrontatutkimus tornionlaaksolaisuudesta vanhimpien aapualaisten arjessa ja tulevaisuudessa/ Tarja Tapio*. - Jyv\xe4skyl\xe4: Jyv\xe4skyl\xe4n yliopisto, 2010. - 261 s. - Jyv\xe4skyl\xe4 studies in education, psychology and social research; 395 - ISBN 978-951-39-3981-6 (nid.)',
  'researcher': 'Tapio Tarja',
  'section': 'julkaisut',
  'sort_date': 2010,
  'title': u'"Meil\xe4 on kaikila samanlaiset tarinat": tarinankerrontatutkimus tornionlaaksolaisuudesta vanhimpien aapualaisten arjessa ja tulevaisuudessa',
  'tutka_date': 2010},
 {'custom_reference': u'Aaltonen, T. (2010).<em> "Taiteilija ei vanhene": haastattelututkimus kuvataiteilijoiden ik\xe4\xe4ntymiskokemuksista taidemaailmassa.</em> Jyv\xe4skyl\xe4, Finland: Jyv\xe4skyl\xe4n yliopisto. Jyv\xe4skyl\xe4 studies in education, psychology and social research, 397.',
  'editors': '',
  'getRemoteUrl': 'http://tutka.jyu.fi/tutka/julkaisut/41592',
  'id': 'julkaisut_41592',
  'lib_reference': u'"Taiteilija ei vanhene": haastattelututkimus kuvataiteilijoiden ik\xe4\xe4ntymiskokemuksista taidemaailmassa/ Terhi Aaltonen*. - Jyv\xe4skyl\xe4: Jyv\xe4skyl\xe4n yliopisto, 2010. - 216 s. - Jyv\xe4skyl\xe4 studies in education, psychology and social research; 397 - ISBN 978-951-39-4019-5 (nid.)',
  'researcher': 'Aaltonen Terhi',
  'section': 'julkaisut',
  'sort_date': 2010,
  'title': u'"Taiteilija ei vanhene": haastattelututkimus kuvataiteilijoiden ik\xe4\xe4ntymiskokemuksista taidemaailmassa',
  'tutka_date': 2010},
 {'custom_reference': u"Siisi\xe4inen, L. (2010).<em> Foucault's voices: toward the political genealogy of the auditory-sonorous.</em> Jyv\xe4skyl\xe4, Finland: University of Jyv\xe4skyl\xe4. Jyv\xe4skyl\xe4 studies in education, psychology and social research, 384.",
  'editors': '',
  'getRemoteUrl': 'http://tutka.jyu.fi/tutka/julkaisut/40383',
  'id': 'julkaisut_40383',
  'lib_reference': u"Foucault's voices: toward the political genealogy of the auditory-sonorous/ Lauri Siisi\xe4inen*. - Jyv\xe4skyl\xe4: University of Jyv\xe4skyl\xe4, 2010. - 207 s. - Jyv\xe4skyl\xe4 studies in education, psychology and social research; 384 - ISBN 978-951-39-3818-5 (nid.)",
  'researcher': u'Siisi\xe4inen Lauri',
  'section': 'julkaisut',
  'sort_date': 2010,
  'title': "Foucault's voices: toward the political genealogy of the auditory-sonorous",
  'tutka_date': 2010},
 {'custom_reference': u'Lyyra, P. (2010).<em> Higher-order theories of consciousness: an appraisal and application.</em> Jyv\xe4skyl\xe4, Finland: University of Jyv\xe4skyl\xe4. Jyv\xe4skyl\xe4 studies in education, psychology and social research, 387.',
  'editors': '',
  'getRemoteUrl': 'http://tutka.jyu.fi/tutka/julkaisut/40394',
  'id': 'julkaisut_40394',
  'lib_reference': u'Higher-order theories of consciousness: an appraisal and application/ Pessi Lyyra*. - Jyv\xe4skyl\xe4: University of Jyv\xe4skyl\xe4, 2010. - 163 s. - Jyv\xe4skyl\xe4 studies in education, psychology and social research; 387 - ISBN 978-951-39-3848-2 (nid.)',
  'researcher': 'Lyyra Pessi',
  'section': 'julkaisut',
  'sort_date': 2010,
  'title': 'Higher-order theories of consciousness: an appraisal and application',
  'tutka_date': 2010},
 {'custom_reference': u'Gemechu, D. (2010).<em> The implementation of a multilingual education policy in Ethiopia: the case of Afaan Oromoo in primary schools of Oromia Regional State.</em> Jyv\xe4skyl\xe4, Finland: University of Jyv\xe4skyl\xe4. Jyv\xe4skyl\xe4 studies in education, psychology and social research, 389.',
  'editors': '',
  'getRemoteUrl': 'http://tutka.jyu.fi/tutka/julkaisut/40597',
  'id': 'julkaisut_40597',
  'lib_reference': u'The implementation of a multilingual education policy in Ethiopia: the case of Afaan Oromoo in primary schools of Oromia Regional State/ Dereje Terefe Gemechu*. - Jyv\xe4skyl\xe4: University of Jyv\xe4skyl\xe4, 2010. - 266 s. - Jyv\xe4skyl\xe4 studies in education, psychology and social research; 389 - ISBN 978-951-39-3870-3 (nid.)',
  'researcher': 'Gemechu Dereje Terefe',
  'section': 'julkaisut',
  'sort_date': 2010,
  'title': 'The implementation of a multilingual education policy in Ethiopia: the case of Afaan Oromoo in primary schools of Oromia Regional State',
  'tutka_date': 2010},
 {'custom_reference': u'Niemi, M. (2010).<em> Moraalij\xe4rjestyst\xe4 tuottamassa: tutkimus poliisity\xf6st\xe4 lasten parissa.</em> Jyv\xe4skyl\xe4, Finland: Jyv\xe4skyl\xe4n yliopisto. Jyv\xe4skyl\xe4 studies in education, psychology and social research, 391.',
  'editors': '',
  'getRemoteUrl': 'http://tutka.jyu.fi/tutka/julkaisut/41022',
  'id': 'julkaisut_41022',
  'lib_reference': u'Moraalij\xe4rjestyst\xe4 tuottamassa: tutkimus poliisity\xf6st\xe4 lasten parissa/ Minna  Niemi*. - Jyv\xe4skyl\xe4: Jyv\xe4skyl\xe4n yliopisto, 2010. - 190 s. - Jyv\xe4skyl\xe4 studies in education, psychology and social research; 391 - ISBN 978-951-39-3937-3 (nid.)',
  'researcher': 'Niemi Minna ',
  'section': 'julkaisut',
  'sort_date': 2010,
  'title': u'Moraalij\xe4rjestyst\xe4 tuottamassa: tutkimus poliisity\xf6st\xe4 lasten parissa',
  'tutka_date': 2010}]


